### ISSUE TITLE
TODOs after python-tools conversion

### ISSUE THREAD

**Issue by patcon** [mission-impossible-android/mission-impossible-android#44]
Keeping track of a few smaller items 

- [x] 1. add `--build` flag to `mia install` => https://github.com/mission-impossible-android/mission-impossible-android/pull/64
- [x] 2. add instructions for checking shasum during os download https://github.com/patcon/mission-impossible-android/pull/43#issuecomment-88697697
- [x] 3. ~~extract `update-binary' during build, not configure https://github.com/patcon/mission-impossible-android/pull/43#discussion_r27678127 (unsure of this...)~~ => #50
- [x] 4. rework app install model https://github.com/patcon/mission-impossible-android/pull/43#discussion_r27678127 -- PR https://github.com/patcon/mission-impossible-android/pull/47
- [x] 5. ~~mirror package directory structure in definition (remove yaml mapping) https://github.com/patcon/mission-impossible-android/pull/43#discussion_r27678127~~ => #78
- [ ] ~~6. make wizard optional (`--interactive` flag?) https://github.com/patcon/mission-impossible-android/pull/43#discussion_r27678127~~
- [ ] 7. use consistent terminology (between yaml and pycode and index.xml)
- [x] 8. `mia definition dl-apps <def>` shouldn't download from scratch each run (something speedy like `wget --continue`) => #68
- [x] 9. allow missing `vercode` to be understood as "unpinned" version for settings.yaml, and fetches latest for lock

cc: @SchnWalter

**Comment by SchnWalter** [comment]
I've setup the `build` command to generate the update.zip into a separate `builds` folder, and after playing around I realized that it's better to either generate the update zip in the workspace root or in the resources folder. And it is more confusing when you have the build folder created by the python setuptools.

What do you think? The "workspace" root? or the resources folder?

**Comment by patcon** [comment]
I think it makes sense to have it in the definition if it's specific to that. Right now, the resources dir is pretty much a cache in my mind, and that's the reason it makes sense to be in the root

**Comment by patcon** [comment]
Just to provide clarity, this is what I was hoping we could work towards for the settings.yml:
https://gist.github.com/patcon/71006988eb7a39831551

- matching up with index.xml naming
- versioning config
- single app array, with defaults for repo and install type that can be overriden by adding a hash key
- no `vercode` required by default, but can be supplied
- no yaml mapping of every file

Thoughts on any of that? :)

**Comment by patcon** [comment]
Hey @SchnWalter, I see it's [doable in python](https://code.activestate.com/recipes/83208-resuming-download-of-a-file/), but as for resuming a download, is there any reason we can't just shell out to `wget` or `curl`? I can't think of solid reason not to, especially considering we're only interested in supporting linux

**Comment by SchnWalter** [comment]
Instead of the `--interactive` for the number 6 item I would like to suggest a `--settings=~/s.yaml` option this way you could use your own settings file and not have to go through all the questions.

So the `deffintion create` command will look like this:
```
mia definition create [--cpu=<cpu>] [--force] [--template=<template>] [--settings=<settings>] [<definition>]
```
Where `<settings>` would be either an URL poiting to a remote settings yaml file or a local file that would be copied inside the generated definition.

P.S. In the mean time could you please merge also the packaging branch before we need to fix conflicts with new changes.

**Comment by patcon** [comment]
Actually, 6 would strike me as a non-issue if we shipped with some default definitions -- i just prefer for someone to be able to build the "official" main project in a command or two :)

I'm working on some other things right now, but I'll def prioritize #46 before I touch anything else

**Comment by SchnWalter** [comment]
we can drop issue 3 and continue the discussion on #50

**Comment by patcon** [comment]
:+1: (edited OP)

**Comment by patcon** [comment]
I think we're good to close this. i'll aim not to start monolithic issues like this anymore
